////////////////////////////////////////////////////////////////////////////////
//    ScopeFun Oscilloscope ( http://www.scopefun.com )
//    Copyright (C) 2016 - 2019 David Košenina
//
//    This file is part of ScopeFun Oscilloscope.
//
//    ScopeFun Oscilloscope is free software: you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation, either version 3 of the License, or
//    (at your option) any later version.
//
//    ScopeFun Oscilloscope is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.
//
//    You should have received a copy of the GNU General Public License
//    along with this ScopeFun Oscilloscope.  If not, see <http://www.gnu.org/licenses/>.
//
////////////////////////////////////////////////////////////////////////////////
#ifndef __ScopeFunServerUI__
#define __ScopeFunServerUI__

/**
@file
Subclass of ServerUI, which is generated by wxFormBuilder.
*/

#include "serverui.h"

//// end generated include

/** Implementing ServerUI */
class ScopeFunServerUI : public ServerUI
{
protected:
    // Handlers for ServerUI events.
    void ServerUIOnActivate(wxActivateEvent& event);
    void ServerUIOnClose(wxCloseEvent& event);
    void m_button1OnButtonClick(wxCommandEvent& event);
    void m_button2OnButtonClick(wxCommandEvent& event);
    void m_checkBox1OnCheckBox(wxCommandEvent& event);
    void m_checkBox2OnCheckBox(wxCommandEvent& event);
    void m_textCtrl3OnTextEnter(wxCommandEvent& event);
public:
    /** Constructor */
    ScopeFunServerUI(wxWindow* parent);
    //// end generated class members
public:
    void msgVersion();




};

#endif // __ScopeFunServerUI__
