////////////////////////////////////////////////////////////////////////////////
//    ScopeFun Oscilloscope ( http://www.scopefun.com )
//    Copyright (C) 2016 - 2019 David Košenina
//
//    This file is part of ScopeFun Oscilloscope.
//
//    ScopeFun Oscilloscope is free software: you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation, either version 3 of the License, or
//    (at your option) any later version.
//
//    ScopeFun Oscilloscope is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.
//
//    You should have received a copy of the GNU General Public License
//    along with this ScopeFun Oscilloscope.  If not, see <http://www.gnu.org/licenses/>.
//
////////////////////////////////////////////////////////////////////////////////
#ifndef __OsciloskopStorage__
#define __OsciloskopStorage__

/**
@file
Subclass of Storage, which is generated by wxFormBuilder.
*/

#include "osc.h"

//// end generated include

/** Implementing Storage */
class OsciloskopStorage : public Storage
{
protected:
    // Handlers for Storage events.
    void m_choiceStorageOnChoice(wxCommandEvent& event);
    void m_textCtrlStorageOnTextEnter(wxCommandEvent& event);
    void m_choicePacketSizeOnChoice(wxCommandEvent& event);
    void m_buttonOkOnButtonClick(wxCommandEvent& event);
    void m_buttonDefaultOnButtonClick(wxCommandEvent& event);
    void m_buttonCancelOnButtonClick(wxCommandEvent& event);
public:
    /** Constructor */
    OsciloskopStorage(wxWindow* parent);
    //// end generated class members


};

#endif // __OsciloskopStorage__
