////////////////////////////////////////////////////////////////////////////////
//    ScopeFun Oscilloscope ( http://www.scopefun.com )
//    Copyright (C) 2016 - 2019 David Košenina
//
//    This file is part of ScopeFun Oscilloscope.
//
//    ScopeFun Oscilloscope is free software: you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation, either version 3 of the License, or
//    (at your option) any later version.
//
//    ScopeFun Oscilloscope is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.
//
//    You should have received a copy of the GNU General Public License
//    along with this ScopeFun Oscilloscope.  If not, see <http://www.gnu.org/licenses/>.
//
////////////////////////////////////////////////////////////////////////////////
#ifndef __OsciloskopConnection__
#define __OsciloskopConnection__

/**
@file
Subclass of Connection, which is generated by wxFormBuilder.
*/

#include "osc.h"

//// end generated include

/** Implementing Connection */
class OsciloskopConnection : public Connection
{
protected:
    // Handlers for Connection events.
    void m_choiceConnectionOnChoice(wxCommandEvent& event);
    void m_textCtrlIPOnTextEnter(wxCommandEvent& event);
    void m_textCtrlPortOnTextEnter(wxCommandEvent& event);
    void m_checkBoxConnectedOnCheckBox(wxCommandEvent& event);
    void m_buttonConnectOnButtonClick(wxCommandEvent& event);
    void m_buttonDisconnectOnButtonClick(wxCommandEvent& event);
    void m_buttonOkOnButtonClick(wxCommandEvent& event);
    void m_buttonDefaultOnButtonClick(wxCommandEvent& event);
    void m_buttonCancelOnButtonClick(wxCommandEvent& event);
public:
    /** Constructor */
    OsciloskopConnection(wxWindow* parent);
    //// end generated class members
public:
    void setConnectedCheckBox(int value);



};

#endif // __OsciloskopConnection__
